repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '2.1.1'
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: https://github.com/pycqa/flake8
    rev: '7.2.0'
    hooks:
      - id: flake8
