services:
  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    env_file:
      - ../.env
    volumes:
      - ./alembic:/app/alembic
      - ./test.db:/app/database.db

  bot:
    build:
      context: ..
      dockerfile: docker/bot.Dockerfile
    env_file:
      - ../.env