name: coverage

on:
  push:
#    branches:
#      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
          poetry add --dev pytest pytest-cov
      - run: poetry install --no-interaction

      # And finally run tests. I'm using pytest and all my pytest config is in my `pyproject.toml`
      # so this line is super-simple. But it could be as complex as you need.
      - name: Run tests with coverage 
        run: poetry run pytest --cov=src --cov-report=term-missing tests/
      - name: Run mutations
        run:  poetry run mutmut run --paths-to-mutate=src/bot
